### ISSUE TITLE
authentication via google/twitter/github is broken

### ISSUE THREAD

**Issue by melezhik** [metacpan/metacpan-web#1819]
Hi I am trying to authenticate ( get logged in to my profile ). to metacpan.org

1. when using authentication via my github account the system silently return me back to the current page and I still see at the up right corner that I am not logged in ( sign i link  still appears )

2. the same behavior for attempt with twitter account

3. when using authentication vua google account a I redirected to [page](https://accounts.google.com/o/oauth2/auth?client_id=265904441292.apps.googleusercontent.com&response_type=code&redirect_uri=https%3A%2F%2Ffastapi.metacpan.org%2Flogin%2Fgoogle&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile) with content:

```
400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, https://fastapi.metacpan.org/login/google, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/265904441292.apps.googleusercontent.com?project=265904441292 to update the authorized redirect URIs.

Learn more
Request Details

    scope=https://www.googleapis.com/auth/userinfo.profile
    response_type=code
    redirect_uri=https://fastapi.metacpan.org/login/google
    client_id=265904441292.apps.googleusercontent.com

That’s all we know.
```

**Comment by hakonhagland** [comment]
I have the same problem. When I try log in with Google I get the message `400. That’s an error` as @melezhik does. Also the same behavior as @melezhik with GitHub.

**Comment by oalders** [comment]
Oops! The GitHub login should now be working.

**Comment by melezhik** [comment]
Hi Olaf! Have just tried to log in via github, but the issue is still here.

**Comment by choroba** [comment]
Same problem here. Clicking on "GitHub" reloads the page, but "Sign in" stays in the top right corner.

**Comment by tsibley** [comment]
Hi @melezhik, @choroba, and @hakonhagland.  Thanks for reporting this.  Have you previously been able to login to your metacpan.org accounts with Github/Google/Twitter, or is this your first time?

**Comment by melezhik** [comment]
Hi  @tsibley . I have never used a twitter , but probably it was a github or google account gets used for metacpan authentication.

**Comment by hakonhagland** [comment]
Hi @tsibley. I am not sure what I used, I guess it must have been either google/github. Is it possible to somehow use my CPAN password to login? Now the login dropdown menu has five choices : Facebook, GitHub, Twitter, Google, and OpenID. Also, how does one login with OpenID?

**Comment by choroba** [comment]
Same with me - I don't remember, but I guess I used :octocat: to log in.

**Comment by oalders** [comment]
The GitHub OAuth app issue should be fixed, but maybe the cookies are getting in the way.  Could someone try deleting any MetaCPAN cookies and trying the GitHub login?

**Comment by melezhik** [comment]
This is my story:

1. run firefox on anonymous mode
2. open http://metacpan.org/
3. choose login bia GH ( upper right corner )
4. get reditected to GH login page
5. enter my GH creds here (login and password)
6. then gets redirected back to MetaCPAN site
7. noticed still sign in  block at upper right corner

**Comment by hakonhagland** [comment]
I usually use Google Chrome on Ubuntu 16.04, so I switched to firefox (which I have not used for months) now to see if there could be an issue with cookies. But I get exactly the behavior as described by @melezhik in the comment above.

**Comment by choroba** [comment]
No good news here, either. I tried with GitHub. It asked me to enable MetaCPAN in GitHub, which I did, but then I was again redirected to the title screen with "Sign in" in the top right corner.

**Comment by mfzz** [comment]
I confirmed this also happened to me. Clicking the github through the sign in, and it just reload the page. The sign in on top left corner still sitting there.

**Comment by tyldum** [comment]
+1 for Google
Error: redirect_uri_mismatch
redirect_uri=https://fastapi.metacpan.org/login/google

**Comment by peterdragon** [comment]
Same problem as melezhik.
1) github redirects silently back to metacpan.org, not logged in
2) google gives following OAuth error message on Chrome browser on MacOS Sierra

Error: redirect_uri_mismatch

`The redirect URI in the request, https://fastapi.metacpan.org/login/google, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/265904441292.apps.googleusercontent.com?project=265904441292 to update the authorized redirect URIs.
`

**Comment by putaotao** [comment]
@oalders I delete all metacpan cookie, then try github login, can't work. I want to know how to debug the problem.

**Comment by AnotherOneAckap** [comment]
Hello, I can't login with GitHub too. Tried to clear cookies, browser private mode, revoke access — no luck.
Browser just redirects me back to metacpan, thinking login succeed, but server rejects requests to account info
 https://metacpan.org/account/favorite/list_as_json 403 (Forbidden)

**Comment by faraco** [comment]
The Github login still doesn't worked.

**Comment by smith153** [comment]
Same here. I thought we used to be able to just use our Pause account to log in??

**Comment by stphnlyd** [comment]
It's still broken.

**Comment by vhamon** [comment]
Same here.

**Comment by oalders** [comment]
I'm tempted to switch most of the OAuth over to a small Mojo app that we could mount via Plack.  There are lots of integrations that you get for free:

https://metacpan.org/search?q=distribution:Mojolicious-Plugin-Web-Auth+Mojolicious::Plugin::Web::Auth

https://metacpan.org/search?q=Mojolicious%3A%3APlugin%3A%3AWeb%3A%3AAuth

That would make some of this easier to debug -- at least the OAuth logins.

**Comment by tyldum** [comment]
On metacpan-api:

lib/MetaCPAN/Server/Controller/Login/GitHub.pm
26:                redirect_uri  => $c->uri_for( $self->action_for('index') ),

lib/MetaCPAN/Server/Controller/Login/Google.pm
30:                redirect_uri  => $c->uri_for( $self->action_for('index') ),
57:            redirect_uri  => $c->uri_for( $self->action_for('index') ),

Smells like a reverse proxy mismatch. I assume you either have to register the https://fastapi.metacpan.org/login/google URL with the providers or provide the canonical URL here.

**Comment by putaotao** [comment]
@oalders Good idea

**Comment by BlueT** [comment]
I have no luck with both GitHub and Google login, still.

**Comment by oalders** [comment]
The issue with the Google App is that the callback URL has changed but we no longer have access to the Google OAuth app.  I've created a new app.  We can test this out once the new credentials have been deployed.

**Comment by oalders** [comment]
Could anyone who is having issues with the Google login try it now?  I just tested it for myself and was able to authenticate.

**Comment by melezhik** [comment]
Hi @oalders  Unfortunately the issue is still here.  Though "Error: redirect_uri_mismatch" message is no more appeared at browser.

I removed cookies for metacpan.* and tried in Firefox anonymous mode as well. I get redirected to my google(gmail) account, I choose it, allowing access for metacpan then gets redirected back to metacpan , but still see "sign in" link at the upper right corner, as if I'd never get loggin

**Comment by melezhik** [comment]
Probably I missed something?

**Comment by mydimension** [comment]
It took my through the process of selecting my google ID and verifying the app permissions to be granted, but metacpan.org still shows me as not logged in

**Comment by oalders** [comment]
So, at least the URI mismatch is fixed.  To confirm, this is _not_ just an issue with Firefox?  Can I get sense of which Browser/OS combos we're looking at here?

**Comment by melezhik** [comment]
Hi @oalders , I have not tried a chromium yet, but it does not work at safari as well

**Comment by putaotao** [comment]
chromium-browser --version
Using PPAPI flash.
 --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version=
Chromium 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04

First click sign in, redirect to google auth, allow access, but sign in still show. Then click sign in(google) contiune, no response, remove all metacpan cookie, click sign in(google), no response.

**Comment by sergeykolychev** [comment]
@oalders Hi there, the login via website does not work, be it github/google/facebook/twitter or pause.
The login via fastapi does work and shows valid json (show that I am logged in) but it has no effect on the website, still displays sign in in right corner.
Verified the issue in latest chrome and firefox.

**Comment by niceperl** [comment]
According the stats of "metacpan weekly report" at http://niceperl.blogspot.com/, the number of clicks on the ++ button is getting lower. I think it's important to fix this issue.

**Comment by oalders** [comment]
@niceperl which version of the API are you currently using?

**Comment by niceperl** [comment]
I haven't used any API, the problem refers to web login al metacpan.org

**Comment by oalders** [comment]
@niceperl which version of the API is the report using?

**Comment by niceperl** [comment]
It uses [MetaCPAN::Client](https://metacpan.org/pod/MetaCPAN::Client), version 2.000000

**Comment by sergeykolychev** [comment]
When this will be fixed ? Why this important problem is allowed to languish for so long ? 
I am willing to help you to debug this by providing any additional info that you may need.
Apis do work, the problem is with the website itself, likely on js layer.

**Comment by oalders** [comment]
@sergeykolychev someone just needs to pick this up and fix it.  My personal schedule is pretty limited right now and I'm at a loss as to what the actual problem might be, so I haven't tackled it.  This is all open source, top to bottom.  Anyone can fire up the VM and try to troubleshoot it.  The only things that are secret are the configuration files with OAuth secrets etc.

The classic problem with this project is that there are lots of users, but very few contributors.  We do our best to keep things running, but there's only so much we can do.  We all agree that it's an important bug, but it's just finding the time to get it done.

There's a chance that our Fastly config is getting in the way.  @ranguard has assured me that this is not the case, but it's something to keep in mind.  If anyone wants to tackle this, we will offer our full support in working through it.

**Comment by sergeykolychev** [comment]
Understood, I will try to debug this tomorrow.

**Comment by sergeykolychev** [comment]
@oalders 
I played a bit with the site and found following
1) despite to the fact that Sign in link still present on right side I actually able to login
2) I can access and browse my info via following uris (they work and show correct info)
https://metacpan.org/account/identities
https://metacpan.org/account/profile
https://metacpan.org/account/settings
https://metacpan.org/account/turing
3) However the uris
https://metacpan.org/account/favorite/list
https://metacpan.org/account/favorite/list_as_json
return 403 code (Forbidden) and display 
```
Forbidden
You don't have permission to access this resource
```
message.
I wonder if this https://github.com/metacpan/metacpan-web/commit/0362ec7fe84215b0c13466d2370877ad72bc2ca8
has anything to do with this ?
Seeing as I am logged in and only the favorites uris do not work, can it be related to me being a new user ? Can you try to create a new user and see if you'll have any similar problems ?
Sorry at this point, I do not have any direct pull for you :-)

**Comment by haarg** [comment]
I believe I have a fix for this now: #1860.

@sergeykolychev thank you for noticing that the account pages were working.  This pointed me directly to where the problem was.

The dashboard is a separate issue, #1801.

**Comment by oalders** [comment]
The fix has been merged and will be deployed within the hour.  Could people report back on whether we're ready to close this ticket yet?

**Comment by tyldum** [comment]
Works for me, but seems to have uncovered another issue. I can log in with Google, but my PAUSE identity is no longer linked and my favorites are gone. If I reconnect PAUSE I get back my favorites, but then the Google association is gone again and I can't log in without repeating this in an endless loop. On Mar 20, 2017 4:49 AM, Olaf Alders <notifications@github.com> wrote:The fix has been merged and will be deployed within the hour.  Could people report back on whether we're ready to close this ticket yet?

**Comment by melezhik** [comment]
Hi, works for me, logout/login safari+github , can see my favorites. Have not  tried log in with pause

**Comment by faraco** [comment]
Work fine with Github login and PAUSE.

**Comment by niceperl** [comment]
It works for me. 
The favorites list is different from one identity (GITHUB) to another (PAUSE)

**Comment by hakonhagland** [comment]
Seems to work for me with PAUSE and Google login from Google Chrome, Ubuntu 16.10. The favorites are different between different identities as mentioned by @niceperl
